# Comment to be posted to on first time issues

sgwtProbotNewIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

sgwtProbotNewIssueSayHi: true

sgwtProbotNewIssueNpmIssue: true

sgwtProbotCloseIssueReport: true

sgwtProbotIssueCommentBot: true
